name: Manual Package

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Build target script to run'
        required: true
        default: build-all
        type: choice
        options:
          - build-all
          - build-chunk

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo bash ./install-dazzle.sh

      - name: Start BuildKit and local registry
        run: |
          chmod +x ./start-dazzle.sh
          sudo bash ./start-dazzle.sh &
          sleep 5 # Wait for BuildKit and registry to start

      - name: prebuild setup
        run: |
          chmod +x ./prebuild-dazzle.sh
          sudo bash ./prebuild-dazzle.sh
      
      - name: Run build script
        run: |
          chmod +x ./${{ github.event.inputs.target }}.sh
          sudo bash ./${{ github.event.inputs.target }}.sh
      - name: sync docker
        run: |
          chmod +x ./skope-sync.sh
          sudo bash ./skope-sync.sh

      - name: Cleanup
        if: always()
        run: |
          docker rm -f registry || true
          if [ -f /tmp/buildkitd.pid ]; then kill "$(cat /tmp/buildkitd.pid)" || true; fi
